# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b515fb424cd161881048cc4f60ee6a48afb075f4df22f43e3090a8bbf8c0e3f3667651b15728100bd21b46c92b8f3ddfc91ef55ab789e5c8820e032a9e3664e5

test:
  secret_key_base: 928e77033cdc84fc32a1005b11c2cafd4f225086c80fc21acca343a7ea97a350bbdb19dfe5929996a8a3e0c562cc4e968576bfc4fa052b7ac1c70d1d4e6212f4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
